<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWmxB6dK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWmxB6dK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWmxB6dK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWmxB6dK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWmxB6dK\App_KernelDevDebugContainer([
    'container.build_hash' => 'WmxB6dK',
    'container.build_id' => '88af1cfc',
    'container.build_time' => 1653152299,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWmxB6dK');
