<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL6oEZQN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL6oEZQN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL6oEZQN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL6oEZQN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL6oEZQN\App_KernelDevDebugContainer([
    'container.build_hash' => 'L6oEZQN',
    'container.build_id' => 'cad8e9f6',
    'container.build_time' => 1654757841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL6oEZQN');
