<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWx8NrpW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWx8NrpW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWx8NrpW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWx8NrpW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWx8NrpW\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wx8NrpW',
    'container.build_id' => 'af185efb',
    'container.build_time' => 1652594526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWx8NrpW');
